addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: b82e7178-0701-4700-98cb-ac64dbe16263
cache:
  directories: [$HOME/.m2/repository]
install: /bin/true
jdk: [oraclejdk8]
language: java
script: [mvn install -Dskip.unit.tests=true -Dmaven.javadoc.skip=true -V -B, 'mvn
    clean test coveralls:report -V -P coverage', jdk_switcher use openjdk7, mvn test,
  ./df-build.sh]
sudo: false
# Modified by Insights Service at 2016-02-28 11:26:12.627493
