addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: e834cef4-c2c6-4522-9b57-5a05a3ea39c0
cache:
  directories: [$HOME/.m2/repository]
install: /bin/true
jdk: [oraclejdk8]
language: java
script: [mvn install -Dskip.unit.tests=true -Dmaven.javadoc.skip=true -V -B, 'mvn
    clean test coveralls:report -V -P coverage', jdk_switcher use openjdk7, mvn test,
  ./df-build.sh]
sudo: false
# Modified by Insights Service at 2016-03-20 14:21:47.911405
