addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: facec12b-5258-48ce-a0f0-c6eeb91333a0
cache:
  directories: [$HOME/.m2/repository]
install: /bin/true
jdk: [oraclejdk8]
language: java
script: [mvn install -Dskip.unit.tests=true -Dmaven.javadoc.skip=true -V -B, 'mvn
    clean test coveralls:report -V -P coverage', jdk_switcher use openjdk7, mvn test,
  ./df-build.sh]
sudo: false
# Modified by Insights Service at 2016-02-26 16:20:24.960176
